[build]
  command = "npm install"
  publish = "."

[build.environment]
  # Your environment variables

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[functions]
  directory = "netlify/functions"
