[build]
  # Remove custom command to let Netlify auto-detect
  # This will automatically run npm install

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[functions]
  directory = "netlify/functions"
