[build]
  publish = "public"
  command = "echo 'Build complete'"

[build.environment]
  # These will be set in Netlify UI
  # DVLA_API_KEY = ""
  # DVLA_TEST_API_KEY = ""

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[functions]
  directory = "netlify/functions"